### PR TITLE
Allow declaring exchanges from STOMP

### PR DESCRIPTION
**Pull request by sparkyb**
The STOMP plugin uses rabbit_routing_util:ensure_endpoint to declare a queue
based on a destination path. However, if that path is an exchange, currently
it will not declare the exchange, it must already exist. With this change, if
a declare_exchange parameter is passed and set to true, the destination
exchange will be declared. Additional parameters may be passed to specify
exchange properties: type, durable, auto_delete, and arguments. All of these
must be prefixed with exchange_ to distinguish them from parameters that
specify similarly named properties of the queue the exchange will be bound to.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@sparkyb Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/rabbitmq?repositoryId=rabbitmq/rabbitmq-erlang-client&pullRequestId=131)!

[Click here](https://cla.pivotal.io/sync/rabbitmq?repositoryId=rabbitmq/rabbitmq-erlang-client&pullRequestId=131) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@sparkyb Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/rabbitmq?repositoryId=rabbitmq/rabbitmq-erlang-client&pullRequestId=131)!

**Review by michaelklishin — COMMENTED** [review]
This is a dependency of https://github.com/rabbitmq/rabbitmq-stomp/pull/144.

**Comment by lukebakken** [comment]
New pull request: https://github.com/rabbitmq/rabbitmq-server/pull/2637

**Comment by lukebakken** [comment]
New pull request: https://github.com/rabbitmq/rabbitmq-server/pull/2639

**Pull request closed without merging**
