### PR TITLE
Take connection / channel limits into account

### PR DESCRIPTION
**Pull request by lukebakken**
Starting the supervisor children could trigger a `not_allowed` if
connection or channel limits are exceeded. This change avoids the
`badmatch` error.

See:
https://github.com/rabbitmq/rabbitmq-server/runs/1243633742?check_suite_focus=true

### CODE REVIEW

**Review by dumbbell — APPROVED** [review]
Looks good to me!

Could you please rebase on the latest master? The Travis configuration was updated and it should work now.

**Comment by lukebakken** [comment]
@dumbbell rebased. This PR isn't going to magically fix the test I think, we'll just not have the `badmatch` anymore.

**Comment by michaelklishin** [comment]
@dumbbell that's a good catch.

**Comment by dumbbell** [comment]
> @dumbbell that's a good catch.

Thanks!

**Comment by lukebakken** [comment]
Backported to `v3.8.x`

**Pull request merged**
