### PR TITLE
Use Ranch for TCP acceptor pool

### PR DESCRIPTION
**Pull request by essen**
Part of https://github.com/rabbitmq/rabbitmq-server/issues/260.

This change is necessary because the ssl_socket record is gone.

### CODE REVIEW

**Comment by michaelklishin** [comment]
After merging master in, `make tests` fails with

```
BOOT FAILED
===========

Error description:
   {could_not_start,rabbit,
       {{case_clause,
            {error,
                {{undef,
                     [{ranch,child_spec,
                          [{acceptor,{0,0,0,0,0,0,0,0},5672},
                           1,ranch_tcp,
                           [{port,5672},
                            {ip,{0,0,0,0,0,0,0,0}},
                            {max_connections,infinity},
                            {ack_timeout,5000},
                            {connection_type,supervisor},
                            inet6,binary,
                            {backlog,128},
                            {nodelay,true},
                            {linger,{true,0}},
                            {exit_on_close,false},
                            {active,false},
                            {packet,raw},
                            {reuseaddr,true}],
                           rabbit_connection_sup,[]],
                          []},
                      {tcp_listener_sup,init,1,
                          [{file,"src/tcp_listener_sup.erl"},{line,59}]},
                      {supervisor,init,1,[{file,"supervisor.erl"},{line,272}]},
                      {gen_server,init_it,6,
                          [{file,"gen_server.erl"},{line,328}]},
                      {proc_lib,init_p_do_apply,3,
                          [{file,"proc_lib.erl"},{line,240}]}]},
                 {child,undefined,'rabbit_tcp_listener_sup_:::5672',
                     {tcp_listener_sup,start_link,
                         [{0,0,0,0,0,0,0,0},
                          5672,ranch_tcp,
                          [inet6,binary,
                           {backlog,128},
                           {nodelay,true},
                           {linger,{true,0}},
                           {exit_on_close,false},
                           {active,false},
                           {packet,raw},
                           {reuseaddr,true}],
                          rabbit_connection_sup,[],
                          {rabbit_networking,tcp_listener_started,[amqp]},
                          {rabbit_networking,tcp_listener_stopped,[amqp]},
                          "TCP Listener"]},
                     transient,infinity,supervisor,
                     [tcp_listener_sup]}}}},
        [{rabbit_networking,start_listener0,4,
             [{file,"src/rabbit_networking.erl"},{line,305}]},
         {rabbit_networking,'-start_listener/4-lc$^0/1-0-',4,
             [{file,"src/rabbit_networking.erl"},{line,294}]},
         {rabbit_networking,start_listener,4,
             [{file,"src/rabbit_networking.erl"},{line,294}]},
         {rabbit_networking,'-boot_tcp/0-lc$^0/1-0-',1,
             [{file,"src/rabbit_networking.erl"},{line,125}]},
         {rabbit_networking,boot_tcp,0,
             [{file,"src/rabbit_networking.erl"},{line,125}]},
         {rabbit_networking,boot,0,
             [{file,"src/rabbit_networking.erl"},{line,120}]},
         {rabbit_boot_steps,'-run_step/2-lc$^1/1-1-',1,
             [{file,"src/rabbit_boot_steps.erl"},{line,49}]},
         {rabbit_boot_steps,run_step,2,
             [{file,"src/rabbit_boot_steps.erl"},{line,49}]}]}}
```

`deps/ranch` is at c0566d4d986b9d143a7b066f52383652da5f7f74.

**Comment by michaelklishin** [comment]
The same happens for other sub-projects, so I may have an outdated dependency somewhere else.

**Comment by essen** [comment]
I mentioned this to @dumbbell, try with `ERL_LIBS=.. make tests` for now.

**Comment by michaelklishin** [comment]
Thanks, all tests pass.

**Comment by essen** [comment]
Rebased and updated the commit title.

**Comment by michaelklishin** [comment]
Testing GH notifications.

**Pull request merged**
