### PR TITLE
pass connection_timeout to the SSL upgrade

### PR DESCRIPTION
**Pull request by cooper6581**

### CODE REVIEW

**Comment by michaelklishin** [comment]
Can you please submit this against the `stable` branch?

**Comment by michaelklishin** [comment]
@cooper6581 don't worry about it, I will cherry-pick. Thank you!

**Comment by cooper6581** [comment]
Sorry about that, I got scared.  Thanks @michaelklishin!!

**Comment by michaelklishin** [comment]
Done.

**Comment by michaelklishin** [comment]
Note: this passes the timeout value as is. We should make sure that Federation and Shovel, which accept timeouts in seconds, perform the conversion. This client is used directly as well.

**Comment by cooper6581** [comment]
I tested Federation.  The values end up coming in as milliseconds.  With the URI of `amqps://admin:admin@dev76-dkoupal-rmq02?heartbeat=5&connection_timeout=300` Timeout will end up getting `300`.  I'll try and test with Shovel later today.

**Pull request merged**
